# Generated by Django 3.1.5 on 2021-05-30 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from faker import Faker

fake = Faker()

def add_comments_to_past_feedback(apps, schema_editor):
    FeedbackRequest = apps.get_model('project', 'FeedbackRequest')
    FeedbackRequestComment = apps.get_model('project', 'FeedbackRequestComment')
    User = apps.get_model('project', 'User')
    for feedback_request in FeedbackRequest.objects.filter(edited=True):
        FeedbackRequestComment.objects.create(
            feedback_request=feedback_request,
            editor=User.objects.first(),
            content=fake.words(nb=5),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_install_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='active_editor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_up_feedback_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FeedbackRequestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_request_comments', to=settings.AUTH_USER_MODEL)),
                ('feedback_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='project.feedbackrequest')),
            ],
        ),
        migrations.RunPython(add_comments_to_past_feedback)
    ]
