# Generated by Django 3.1.5 on 2021-06-01 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210530_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='edited',
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='active_editor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_feedback_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
